---
apiVersion: v1
kind: Namespace
metadata:
  name: jx
  labels:
    name: jx
    env: dev
    team: jx
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: externaldns-sa
  namespace: jx
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: boot-sa
  namespace: jx
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kaniko-sa
  namespace: jx
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: storage-sa
  namespace: jx
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-sa
  namespace: jx
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: velero-sa
  namespace: jx
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jx-boot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: boot-sa
  namespace: jx