---
apiVersion: v1
kind: Namespace
metadata:
  name: jx
  labels:
    name: jx
    env: dev
    team: jx
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: boot-sa
  namespace: jx
  annotations:
    iam.gke.io/gcp-service-account: boot-sa@${project_id}.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kaniko-sa
  namespace: jx
  annotations:
    iam.gke.io/gcp-service-account: kaniko-sa@${project_id}.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-sa
  namespace: jx
  annotations:
    iam.gke.io/gcp-service-account: vault-sa@${project_id}.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: externaldns-sa
  namespace: jx
  annotations:
    iam.gke.io/gcp-service-account: externaldns-sa@${project_id}.iam.gserviceaccount.com
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jx-boot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: boot-sa
  namespace: jx