boot:
  clusterName:
  bootGitURL: https://github.com/jenkins-x/jenkins-x-boot-helmfile-config.git
  bootGitRef: master
  environmentGitOwner:
  userEmail:
  projectID:
  provider: gke
  tls:
    production: no
  zone:
  versionsGitURL: https://github.com/jenkins-x/jenkins-x-versions.git
  versionsGitRef: master

secrets:
  adminUser:
    username:
    password:
  hmacToken:
  pipelineUser:
    username:
    email:
    token: