kind: ConfigMap
apiVersion: v1
metadata:
  labels:
  name: boot-secrets-template
data:
  secrets.yaml: |-
    secrets:
      adminUser:
        username: $ADMINUSER_USERNAME
        password: $ADMINUSER_PASSWORD
      hmacToken: $HMACTOKEN
      pipelineUser:
        username: $PIPELINEUSER_USERNAME
        email: $PIPELINEUSER_EMAIL
        token: $PIPELINEUSER_TOKEN