{{- if .Values.secrets.env.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  labels:
  name: boot-secrets-template
data:
  secrets.yaml: |-
    secrets:
      adminUser:
        username: $ADMINUSER_USERNAME
        password: $ADMINUSER_PASSWORD
      hmacToken: $HMACTOKEN
      pipelineUser:
        username: $PIPELINEUSER_USERNAME
        token: $PIPELINEUSER_TOKEN
        email: $PIPELINEUSER_EMAIL        
{{- end -}}